#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "Commit started"

echo "Formatting started ⚙️"
dotnet husky run --name dotnet-format-staged
echo "Formatting finished ✅"

echo "Build started 🏗️"
dotnet build server/src/NutritionPlanner.sln --no-restore
echo "Build finished ✅"

echo "Test started 🧪"
dotnet test server/src/NutritionPlanner.sln --no-restore
echo "Test finished ✅"

echo "Commit finished ✅"